version: '3.4'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER = user0001
      MYSQL_PASSWORD = aAAAaaAaAAglbskf
      MYSQL_ROOT_PASSWORD = secretROOTPasswOrd
      MYSQL_DATABASE = docker

  php:
    build :
      Context : ./
    depends_on:
      -db

  web:
    build :
      Content : ./
    depends_on:
      -php

  volumes:
    - root: /$USER/s4-docker contacts.php /srv/contacts
    - overload: contacts.php config.ini docker/php/conf.d/dev.ini
    - public: /$USER/s4-docker/symfony-contacts/public/ contacts.php /srv/contacts/public :ro

ports:
  - "8080:80"

volumes:
  root:
  overload:

# droits pour vos accès
find . -type d -exec setfacl -m d:u:$USER:rwx {} \;
# droits pour l'admin du conteneur php
find . -type d -exec setfacl -m d:u:200000:rwx {} \;
find . -type d -exec setfacl -m u:200000:rwx {} \;
find . -type f -exec setfacl -m u:200000:rw {} \;
find bin -type f -exec setfacl -m u:200000:rx {} \;
# droits pour l'utilisateur www-data du conteneur php
find . -type d -exec setfacl -m d:u:200082:rx {} \;
find . -type d -exec setfacl -m u:200082:rx {} \;
find . -type f -exec setfacl -m u:200082:r {} \;
# droits pour l'utilisateur nginx du conteneur nginx
find public -type d -exec setfacl -m d:u:200101:rx {} \;
find public -type d -exec setfacl -m u:200101:rx {} \;
find public -type f -exec setfacl -m u:200101:r {} \;
